services:
    inventario-service:
      build:
        context: ./api/inventario
        dockerfile: Dockerfile
      image: lex2804/inventario-sa-g0914-project
      container_name: inventario-sa-g0914-project
      env_file:
        - .env.prod
      ports:
        - "5055:5055"
      restart: always
      networks:
        - sa0914-app-net
