services:
    user-service:
      build:
        context: ./api/userservice
        dockerfile: Dockerfile
      image: lex2804/user-sa-g0914-project
      container_name: user-sa-g0914-project
      env_file:
        - .env.prod
      ports:
        - "5050:5050"
      restart: always
      networks:
        - sa0914-app-net
