services:
    notification-service:
      build:
        context: ./api/NotificationService/email
        dockerfile: Dockerfile
      image: lex2804/email-notification-sa-g0914-project
      container_name: email-notification-sa-g0914-project
      env_file:
        - .env.prod
      ports:
        - "6001:6001"
      restart: always
      networks:
        - sa0914-app-net