services:
    confirmar_pago:
      build:
        context: ./api/Payments/ConfirmarPago
        dockerfile: Dockerfile
      image: pilotuy/sa_confirmarpago
      container_name: sa_confirmarpago
      env_file:
        - .env.prod
      ports:
        - "3112:3112"
      restart: always
      networks:
        - sa0914-app-net

    registrar_pago:
      build:
        context: ./api/Payments/ConfirmarPago
        dockerfile: Dockerfile
      image: pilotuy/sa_registrarpago
      container_name: sa_registrarpago
      env_file:
        - .env.prod
      ports:
        - "3111:3111"
      restart: always
      networks:
        - sa0914-app-net