services:
    name-service:
      build:
        context: ./path_of_dockerfile
        dockerfile: Dockerfile
      image: user/name-sa-g0914-project
      container_name: name-sa-g0914-project
      env_file:
        - .env.prod
      ports:
        - "port:port"
      restart: always
      networks:
        - sa0914-app-net